/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniprojet;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author ABDELAAZIZ
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        Txclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2"}));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Phomemain = new javax.swing.JPanel();
        Pcherche = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txclass = new javax.swing.JComboBox<>();
        Txorigine = new javax.swing.JTextField();
        Txdist = new javax.swing.JTextField();
        Txdate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        Ptickets = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(249, 91, 12));

        Phomemain.setBackground(new java.awt.Color(249, 91, 12));
        Phomemain.setLayout(new javax.swing.BoxLayout(Phomemain, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("l'origine");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("distination");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("class");

        Txclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        Txclass.setToolTipText("");
        Txclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxclassActionPerformed(evt);
            }
        });

        Txorigine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxorigineActionPerformed(evt);
            }
        });

        Txdist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxdistActionPerformed(evt);
            }
        });

        Txdate.setDateFormatString("dd-MM-yyyy");

        jButton1.setText("check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PchercheLayout = new javax.swing.GroupLayout(Pcherche);
        Pcherche.setLayout(PchercheLayout);
        PchercheLayout.setHorizontalGroup(
            PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PchercheLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(Txorigine))
                .addGap(35, 35, 35)
                .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txdist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txdate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PchercheLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Txclass, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        PchercheLayout.setVerticalGroup(
            PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PchercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PchercheLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txclass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PchercheLayout.createSequentialGroup()
                        .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PchercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Txorigine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Txdist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Phomemain.add(Pcherche);

        Ptickets.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Ptickets.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Phomemain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Ptickets, javax.swing.GroupLayout.PREFERRED_SIZE, 1223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Phomemain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ptickets, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxclassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxclassActionPerformed

    private void TxorigineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxorigineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxorigineActionPerformed

    private void TxdistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxdistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxdistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Conndb con=new Conndb();
        String origine=Txorigine.getText();
                String dis=Txdist.getText();
                Date date=new Date(); 
                  try{
                 date=Txdate.getCalendar().getTime();
                  }catch(Exception e){
                    date=new Date(); 
    }
          finally{       
                 java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                 String Datee=String.valueOf(sqlDate);
                 String clas=Txclass.getSelectedItem().toString();
                  System.out.println("cl"+clas+"cs");
                
        String[][] data=con.chercher(origine,dis,Datee,clas);
        
         JPanel jp = new JPanel();
          jp.setLayout(new BoxLayout(jp, BoxLayout.PAGE_AXIS));
          int i;
        for(i=0;i<data.length;i++){
              cards ticket=new miniprojet.cards(data[i][0],data[i][1],data[i][2],data[i][3],data[i][4]);
              ticket.setBorder(BorderFactory.createLineBorder(Color.black));
              
              
            
              
              
jp.add(ticket);
jp.revalidate();
 ticket.Breserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 BreserveActionPerformed(evt);
            }

                  
        }); 
        }
      Ptickets.setViewportView(jp); 

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void BreserveActionPerformed(ActionEvent evt) {
                       reserve rese = new miniprojet.reserve();
  setLayout(new java.awt.BorderLayout());
removeAll();
add(rese);
revalidate();
                  }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pcherche;
    private javax.swing.JPanel Phomemain;
    private javax.swing.JScrollPane Ptickets;
    private javax.swing.JComboBox<String> Txclass;
    private com.toedter.calendar.JDateChooser Txdate;
    private javax.swing.JTextField Txdist;
    private javax.swing.JTextField Txorigine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
